fname = input(str("Enter your first name:"))
lname = input(str("Enter your last name:"))
dob = input("Enter your date of birth:")
email = input(str("Enter your email:"))
zcode = input("Enter your zip code:")
city = input(str("Enter your city:"))
state = input(str("Enter your state:"))
race = input(str("Enter your race:"))
age = input("Enter your age:")
sex = input(str("Enter your sex:"))

print(fname)
print(lname)
print(dob)
print(email)
print(zcode)
print(city)
print(state)
print(race)
print(age)
print(sex)